### ISSUE TITLE
Insanity not working.

### ISSUE THREAD

**Issue by gorgdel** [rdutta/runelite-toaextended#1]
Hi, I've noticed the insanity option for wardens, doesn't start the overlay. Is there any other configuration I have to do?

i have checked the location Ids and they match, it just seems that it won't execute, perhaps I am using the plugin incorrectly.

Thanks! Your plugin is amazing btw.

**Comment by rdutta** [comment]
I'm not exactly sure what insanity option you mean, but if the phase3 overlays aren't showing you could try changing the isEnabled() check to WARDEN_P2. Iirc the phase3 plugin/module is enabled after the p3 warden npc spawns, so a manually check is done in the startUp() incase onNpcSpawned doesn't receive the event.

This is assuming you are referring to the hp and slam dir overlays. If none of them are showing (eg prayer indicator) then maybe the config options were set after entering orits a new bug.
